folio-org/mod-erm-usage-harvester

mod-erm-usage-counter41/pom.xml, mod-erm-usage-counter41/src/main/java/org/olf/erm/usage/counter41/Counter4Utils.java, mod-erm-usage-counter41/src/main/java/org/olf/erm/usage/counter41/csv/mapper/JournalReport1Mapper.java, mod-erm-usage-counter41/src/test/java/org/olf/erm/usage/counter41/Counter4UtilsTest.java
=> Add getYearMonthsFromReport and fromString to Counter4Utils

.dockerignore, .gitignore, .gitlab-ci.yml, Dockerfile, docker-compose.yml, ubl/Dockerfile, ubl/Readme.md, ubl/helmchart/.helmignore, ubl/helmchart/Chart.yaml, ubl/helmchart/templates/_helpers.tpl, ubl/helmchart/templates/app.configmap.yaml, ubl/helmchart/templates/app.deployment.yaml, ubl/helmchart/templates/app.service.yaml, ubl/helmchart/templates/db.configmap.yaml, ubl/helmchart/templates/db.deployment.yaml, ubl/helmchart/templates/db.service.yaml, ubl/helmchart/templates/secret.yaml, ubl/helmchart/values.yaml
* added helmchart for deploying to kubernetes
* added .gitlab-ci.yml for GitLab-CI pipeline
* added docker-compose.yml for testing pipeline-jobs locally
=> Enables GitLab-CI Pipeline

mod-erm-usage-harvester-core/pom.xml, pom.xml
Remove okapi-commons dependency as its part of RMB now
Update to latest vert.x version v3.8.4
=> Update RMB to v29.1.0

mod-erm-usage-harvester-bundle/pom.xml
Please see https://issues.folio.org/browse/MODEUSHARV-14
=> Fix logging issue

NEWS.md, mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-nss/pom.xml, mod-erm-usage-harvester-spi/pom.xml, pom.xml
Merge v3.0.1 and correct version to 3.1.0-SNAPSHOT
=> merge-v3.0.1

mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/Launcher.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/EmbeddedPostgresRule.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/PostgresContainerRule.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/WorkerVerticleIT.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/periodic/HarvestTenantJobIT.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/rest/impl/ErmUsageHarvesterPeriodicAPIIT.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/rest/impl/PostDeployImplIT.java, mod-erm-usage-harvester-core/src/test/resources/postgres-conf.json, pom.xml
Upgrade to RMB 33.0.0 and Vert.x 4.1.0.CR1
Remove Guava 19.0 dependency
=> MODEUSHARV-34-upgrade-rmb-v33

descriptors/ModuleDescriptor-template.json
Increase default container memory to 1024MB.
=> MODEUSHARV-42

README.md, descriptors/ModuleDescriptor-template.json, mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/OkapiClient.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/SystemUser.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/periodic/HarvestTenantJob.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/OkapiClientTest.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/SystemUserTest.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/periodic/HarvestTenantJobIT.java, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-nss/pom.xml, mod-erm-usage-harvester-spi/pom.xml, pom.xml
Scheduled harvesting jobs are now executed on behalf of a user.
Therefor `login 7.0` interface is now required.
User credentials are set via env vars.
=> MODEUSHARV-50

mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/periodic/SchedulingUtil.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/periodic/SchedulingUtilTest.java
Fixes bug with scheduled job execution.
=> MODEUSHARV-52

mod-erm-usage-harvester-bundle/pom.xml, pom.xml
Update RMB to 33.2.2, log4j-to-slf4j to 2.16.0
=> MODEUSHARV-54

mod-erm-usage-harvester-cs50/src/main/java/org/olf/erm/usage/harvester/endpoints/DefaultApi.java
Fix attributes_to_show for item reports
=> MODEUSHARV-55

mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs41/src/main/java/org/olf/erm/usage/harvester/endpoints/CS41Impl.java, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-cs50/src/main/java/org/olf/erm/usage/harvester/endpoints/CS50Impl.java, pom.xml
=> MODEUSHARV-69

mod-erm-usage-harvester-cs50/pom.xml, pom.xml
* Use the latest version of `mod-erm-usage-counter` which has fixed a couple vulnerabilities in its dependencies.
* Remove unused `okhttp3.logging-interceptor`.
=> MODEUSHARV-79

descriptors/ModuleDescriptor-template.json, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/periodic/HarvestTenantPeriodicJob.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/periodic/JobInfoJobListener.java, mod-erm-usage-harvester-core/src/main/resources/templates/db_scripts/schema.json, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/periodic/HarvestTenantPeriodicJobIT.java, ramls/schemas/jobInfo.json, ramls/schemas/periodicConfig.json
Adds information to `JobInfo` objects on if and why a harvesting job failed to execute.
=> MODEUSHARV-85

mod-erm-usage-harvester-core/src/main/java/org/folio/rest/impl/ErmUsageHarvesterAPI.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/rest/impl/ErmUsageHarvesterJobsAPIIT.java, pom.xml, ramls/harvester.raml
Add endpoint to delete finished harvesting jobs
=> MODEUSHARV-87

descriptors/ModuleDescriptor-template.json, mod-erm-usage-harvester-core/src/main/java/org/folio/rest/impl/ErmUsageHarvesterAPI.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtConfigurationsClientImpl.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/OkapiClientImpl.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/rest/impl/ErmUsageHarvesterJobsAPIIT.java, ramls/harvester.raml
Adds an okapi timer interface to run cleanup jobs every 30 minutes.
=> MODEUSHARV-92

descriptors/ModuleDescriptor-template.json
Update ModuleDescriptor to include environment variables for Okapi URL and system user credentials.
=> MODEUSHARV-96

Dockerfile, mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/WorkerVerticleIT.java, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-nss/pom.xml, mod-erm-usage-harvester-spi/pom.xml, pom.xml
=> MODEUSHARV-98

pom.xml
Update module dependencies
RMB v35.1.1
Vert.x v4.4.6
=> MODEUSHARV-106

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODEUSHARV-115
See https://github.com/folio-org/mod-erm-usage/pull/184
=> Add support for counter-reports interface 4.0

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODEUSHARV-116
See https://github.com/folio-org/mod-erm-usage/pull/185
=> [MODEUSHARV-116] Add support for aggregator-settings 2.0

descriptors/ModuleDescriptor-template.json, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-110
Renames a couple permissions. Major interface version increase to `erm-usage-harvester 2.0`.
=> [MODEUSHARV-110] Review and cleanup Module Descriptor

README.md
https://folio-org.atlassian.net/browse/MODEUSHARV-118
Updates 'Periodic harvesting' section in `README.md`
=> [MODEUSHARV-118] Update 'Periodic harvesting'  section in README.md

.github/workflows/postgres.yml, mod-erm-usage-harvester-core/src/main/java/org/folio/rest/impl/ErmUsageHarvesterAPI.java, pom.xml, ramls/harvester.raml, ramls/periodic.raml
https://folio-org.atlassian.net/browse/MODEUSHARV-119
* Update RMB, vert.x, aspectj versions
* Update raml-util
* Update API method parameters (remove `lang`, add `totalRecords`)
* Add GA postgres workflow
=> [MODEUSHARV-119] Upgrade RMB to v35.3.0

descriptors/ModuleDescriptor-template.json, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtAggregatorSettingsClientImpl.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtCounterReportsClientImpl.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtUsageDataProvidersClientImpl.java
https://folio-org.atlassian.net/browse/MODEUSHARV-120
Latest updates to `mod-erm-usage`, see https://github.com/folio-org/mod-erm-usage/pull/186, requires:
* Update of method paramters in client implementations
* Update required interface versions
=> [MODEUSHARV-120] Adjust API parameters of client implementations

NEWS.md, mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-nss/pom.xml, mod-erm-usage-harvester-spi/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-122
Release v5.0.0
=> [MODEUSHARV-122] Release v5.0.0

mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-cs51/pom.xml, mod-erm-usage-harvester-cs51/src/main/java/org/olf/erm/usage/harvester/endpoints/CS51Impl.java, mod-erm-usage-harvester-cs51/src/main/java/org/olf/erm/usage/harvester/endpoints/CS51Provider.java, mod-erm-usage-harvester-cs51/src/main/resources/META-INF/services/org.olf.erm.usage.harvester.endpoints.ServiceEndpointProvider, mod-erm-usage-harvester-cs51/src/test/java/org/olf/erm/usage/harvester/endpoints/CS51ImplTest.java, mod-erm-usage-harvester-cs51/src/test/resources/__files/Exception_2010.json, mod-erm-usage-harvester-cs51/src/test/resources/__files/TR.json, mod-erm-usage-harvester-cs51/src/test/resources/__files/TR_invalid.json, mod-erm-usage-harvester-cs51/src/test/resources/__files/TR_with_exception.json, mod-erm-usage-harvester-spi/src/main/java/org/olf/erm/usage/harvester/endpoints/InvalidServiceURLException.java, mod-erm-usage-harvester-spi/src/main/java/org/olf/erm/usage/harvester/endpoints/ServiceEndpoint.java, mod-erm-usage-harvester-spi/src/main/java/org/olf/erm/usage/harvester/endpoints/UnsupportedReportTypeException.java, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-113
* Adds `mod-erm-usage-harvester-cs51` module for harvesting COUNTER release 5.1 reports.
=> [MODEUSHARV-113] Provide ServiceEndpoint implementation for COUNTER 5.1

NEWS.md
* Merge branch b5.0 into master
=> Merge b5.0

CONTRIBUTING.md, pom.xml
* Adds `spotless-maven-plugin` and updates `CONTRIBUTING.md` with usage information.
=> Add `spotless-maven-plugin` and update `CONTRIBUTING.md`

mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtCounterReportsClient.java, mod-erm-usage-harvester-core/src/main/java/org/olf/erm/usage/harvester/client/ExtCounterReportsClientImpl.java, mod-erm-usage-harvester-core/src/test/java/org/olf/erm/usage/harvester/client/ExtCounterReportsClientImplTest.java
https://folio-org.atlassian.net/browse/MODEUSHARV-127
* Consider report release version when fetching valid months
* Consider report release version when fetching a report
=> [MODEUSHARV-127] Counter-reports client not considering report release version

mod-erm-usage-harvester-cs51/src/main/java/org/olf/erm/usage/harvester/endpoints/CS51Impl.java
Updates `CS51Impl` for changes in `mod-erm-usage-counter` `4.2.0-SNAPSHOT`
=> Update CS51Impl for latest snapshot

Dockerfile, Jenkinsfile, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-cs51/pom.xml, mod-erm-usage-harvester-cs51/src/test/java/org/olf/erm/usage/harvester/endpoints/CS51ImplTest.java, mod-erm-usage-harvester-cs51/src/test/resources/__files/TR_with_exception.json, mod-erm-usage-harvester-nss/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-132
* Upgrades to Java 21
* Upgrades RMB to 35.4.0
* Upgrades other dependencies
* Fixes test sample report
=> [MODEUSHARV-132] Upgrade to Java 21

mod-erm-usage-harvester-core/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-133
* Updates `maven-surefire-plugin` and `maven-failsafe-plugin` to `v3.5.2`
=> [MODEUSHARV-133] Update `maven-surefire-plugin` and `maven-failsafe-plugin`

NEWS.md, mod-erm-usage-harvester-bundle/pom.xml, mod-erm-usage-harvester-core/pom.xml, mod-erm-usage-harvester-cs41/pom.xml, mod-erm-usage-harvester-cs50/pom.xml, mod-erm-usage-harvester-cs51/pom.xml, mod-erm-usage-harvester-nss/pom.xml, mod-erm-usage-harvester-spi/pom.xml, pom.xml
https://folio-org.atlassian.net/browse/MODEUSHARV-135
=> [MODEUSHARV-135] Release v5.1.0
